[server]
rules_file = "RulesCorvax.txt"

[ic]
flavor_text = true
punctuation = false

[ooc]
enable_during_round = false

[atmos]
space_wind = true
space_wind_max_velocity = 22.0

[vote]
restart_required_ratio = 0.85
same_type_timeout = 300.0
timerrestart = 30
map_enabled = false
preset_enabled = false
restart_enabled = false
